### ISSUE TITLE
Eloquent Integration

### ISSUE THREAD

**Issue by msaraac** [timgws/QueryBuilderParser#18]
İs there any examples with eloquent ?

**Comment by timgws** [comment]
It's the same as with the QueryBuilder. The only thing to watch out will be joins 👍

Let me know if there is any specific use case that you are having issues with.

The only 'real' reason why there is no real in-depth examples is because an example using Eloquent would be extremely verbose.

**Comment by FBnil** [comment]
Well, in order to use Eloquent, I had to change all 
"use \Illuminate\Database\Query\Builder;" into "use \Illuminate\Database\Eloquent\Builder;" (would love to know how to NOT hack the source, and still get it working)
from there, once you start using nested queries createNestedQuery() will cry about wanting another class. Still trying to figure that one out. If you do not use them, it all works.

The nice thing about eloquent is that you can use "with"

```
public function data(){
  /* default query if it is NULL */
  $queryBuilderJSON =  '{"condition": "AND", "rules": [], "not": false, "valid": true }';
  if(Input::has('querybuilder') && Input::get('querybuilder') != 'null')
	$queryBuilderJSON = Input::get('querybuilder');
  $show_columns = array('id', ....);
  $query = new QueryBuilderParser($show_columns);
  $Q = Users::with('country','educationlevel');
  $queryBuilder = $query->parse($queryBuilderJSON, $Q);
  return Datatables::of($queryBuilder->get())->make(true);
}
```

Now, in order to get that data, in your html (or template), in your DataTable() part, you need to add the data as an array (some examples elsewhere use objects)

```
$('#thetable').DataTable({ 
:
,"fnServerParams": function(aoData){
				console.log('in fnServerParams');
				$.each(datatablesRequest, function(k,v){
					console.log('adding "'+k+'"="'+v+'"');
					aoData[k]=v;
                });
				console.log(aoData);
			}
```
And somewhere else, where you define the filterChange, I inject the extra querybuilder field:
```
    function filterChange() {
        var _json = JSON.stringify( _rules );
        datatablesRequest = { querybuilder: _json };
        // formerly: datatablesRequest = { rules: _rules };
    }
```
Now, to display you do:
```
	$(document).ready(function(){
		$('#thetable').DataTable({
			"processing": true,
			"serverSide": true,
			"scrollX": true,
			"ajax": "users/data",
			"columns": [
			{data:'id'},
			{data:'name'},
			{data:'surname'},
			{data:'email'},
			{data:'country_id'},
			{data:'country.name'},
```

Note that due to the 'with' clause, the field country_id is looked up in the table country, and an object is created for it, which you can access with the dot notation. For that to work, you need a model, containing a statement such as for example:
```
public function country(){
                return $this->belongsTo(Country::class);
        }
```
if you make the country_id hidden, you can now make a dragdrop of country, and even though you see a country in the GUI, the query contains the numeric id of the country.

**Comment by pittfern** [comment]
@FBnil thanks for your notes.

We will have to change some of the QBP code to allow both versions of the Builder classes (from Laravel, that is, the Eloquent Builder and the Query Builder that this code currently supports).

I will work on this a little later.

Thanks,
Tim

**Comment by FBnil** [comment]
let me know if you need a working laravel example of what I stated

**Comment by msaraac** [comment]
thanks its solved
closed

**Comment by Brabudu** [comment]
Hello 
@FBnil thank you for your suggestion about Eloquent. 
About nested queries i've tried to change "return $querybuilder->whereNested(" etc. etc. to "return $querybuilder->where(" (querybuilderparser.php line 114) and it seems to work.

**Comment by FBnil** [comment]
That is great news! Any chance of a pull request?

**Comment by timgws** [comment]
We might need to make a clone of the core QueryBuilderParser if we are going to also add support for Eloquent.

QBP specifically goes out of it's way _not_ to use models that extend Eloquent due to Eloquent using the Active Record pattern. Loading data from the DB using the Builder is much more refined (ie, what is built using the Builder is exactly the SQL query that you expect from the QueryBuilder (the JS plugin).

(Calling `->get()` returns different data if it's from Eloquent vs. Laravel's QueryBuilder.)

**Comment by FBnil** [comment]
Ouch, touch decision! (but whatever the decision, I'll support it (support as in "cheering", I'm not having seas of time, although I can chip in for testing) )
You do not need to support it, but maybe you will lose some userbase? And maintaining two sets of similar files is also more work. (or a mixed if get_class A then this else that scenario)
My only need of Eloquent is the fact that you can use with() and join multiple tables. It can be replaced by a database view (not tested, just an idea), which is harder to change later.

**Comment by timgws** [comment]
Yeah, I was more thinking the mixed case, where support for both Eloquent and QueryBuilder could be built in.

Doubt userbase would be lost, as we are not removing any support :-)

---- On Tue, 17 Oct 2017 08:05:45 +1100 notifications@github.com wrote ----

Ouch, touch decision! (but whatever the decision, I'll support it (support as in "cheering", I'm not having seas of time, although I can chip in for testing) )
You do not need to support it, but maybe you will lose some userbase? And maintaining two sets of similar files is also more work. (or a mixed if get_class A then this else that scenario)
My only need of Eloquent is the fact that you can use with() and join multiple tables. It can be replaced by a database view (not tested, just an idea), which is harder to change later.

**Comment by FBnil** [comment]
@msaraac Can you help testing out the new version? (and then _really_ close the issue)

**Comment by 0ly** [comment]
@timgws Are you still open to supporting both QueryBuilder and EloquentBuilder?

**Comment by timgws** [comment]
100%.




---- On Sat, 28 Apr 2018 08:10:52 +1000 Orlando &lt;notifications@github.com&gt; wrote ----




@timgws Are you still open to supporting both QueryBuilder and EloquentBuilder?

**Comment by lachlanhickey** [comment]
@timgws was this ever implemented?

**Comment by timgws** [comment]
@lachlanhickey sorry, somehow this message skipped my inbox.

Explicit support for Eloquent is non-existant. That being said, you can call newQuery(), and pass that to QBP.

```php
// Users extends \Illuminate\Database\Eloquent\Model
$json = '{"condition": "AND", "rules": [], "not": false, "valid": true }';
$userQuery = (new Users())->newQuery();
$queryBuilder = (new QueryBuilderParser())->parse($json, $userQuery);

// $userQuery contains an SQL query, that you can ->get()
```
